---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Generic ControlStructures InlineControlStructure NotAllowed:
        enabled: false
      Squiz WhiteSpace SuperfluousWhitespace EndLine:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- src/**/*
- test/**/*
- vendor/**/*
- config/**/*