language: php
sudo: required
php:
    - 5.6
install:
    - composer install
services:
    - redis-server
env:
    - DB=mysql
before_script:
    - sudo apt-get update
    - sudo apt-get install python-hiredis
    - wget https://github.com/swoole/swoole-src/archive/v1.9.15.zip
    - unzip swoole-src-1.9.15.zip
    - cd swoole-src-1.9.15
    - phpize
    - ./configure --enable-async-redis
    - make
    - make install
    - cd ..
    - phpenv config-add config.ini
    - app/service user
script:
    - sudo find -L ./core -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - phpunit --bootstrap app/test.php core/Group